version: 2
updates:
  - package-ecosystem: maven
    directory: "/familieforhold-backend/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/familieforhold-frontend/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/alderspensjon-endringssoknad-backend/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/alderspensjon-endringssoknad-frontend/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10