version: 2
updates:
  - package-ecosystem: maven
    directories:
      - /familieforhold-backend/
      - /alderspensjon-endringssoknad-backend/
      - /opptjening-overforomsorgsopptjening-backend/
      - /dinpensjon-backend/
      - /uforetrygd-backend/
      - /inntektsplanleggeren-backend/
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 50
    versioning-strategy: increase

  - package-ecosystem: npm
    directories:
      - /familieforhold-frontend/
      - /alderspensjon-endringssoknad-frontend/
      - /opptjening-overforomsorgsopptjening-frontend/
      - /bytt-bruker-frontend/
      - /representasjon-banner-frontend/
      - /dinpensjon-frontend/
      - /uforetrygd-frontend/
      - /inntektsplanleggeren-frontend/
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 50
    versioning-strategy: increase
    groups:
      designsystemet:
        patterns:
          - '@navikt/ds*'
          - '@navikt/aksel*'
      react:
        patterns:
          - 'react'
          - 'react-dom'

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 10