apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: inntektsplanleggeren-frontend-borger
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
spec:
  groups:
    - name: inntektsplanleggeren-frontend-borger-alerts
      rules:
        - alert: Application is unavailable
          expr: kube_deployment_status_replicas_available{deployment="inntektsplanleggeren-frontend-borger"} == 0
          for: 1m
          annotations:
            consequence: Inntektsplanleggeren borger application is unavailable
            action: "https://logs.adeo.no/app/r/s/IUFfT"
          labels:
            namespace: pensjonselvbetjening # required
            severity: critical
        - alert: Failing deployment
          expr: kube_deployment_status_replicas_unavailable{deployment="inntektsplanleggeren-frontend-borger"} > 1
          for: 5m
          annotations:
            consequence: Inntektsplanleggeren borger failing deployment
            action: "https://logs.adeo.no/app/r/s/IUFfT"
          labels:
            namespace: pensjonselvbetjening # required
            severity: critical
