apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: inntektsplanleggeren-frontend-borger
  namespace: ufore
  labels:
    team: ufore
  annotations:
    nais.io/run-as-user: "101" # nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{ image }}"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
    - https://www.nav.no/uforetrygd/selvbetjening/ny-inntektsplanleggeren
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  idporten:
    enabled: true
    sidecar:
      level: idporten-loa-substantial
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: ufore-unleash-api.nav.cloud.nais.io
      rules:
        - application: inntektsplanleggeren-backend
          cluster: prod-gcp
          namespace: ufore
  env:
    - name: "INNTEKTSPLANLEGGEREN_BACKEND_URL"
      value: "http://inntektsplanleggeren-backend"
    - name: "INNTEKTSPLANLEGGEREN_BACKEND_AUDIENCE"
      value: "prod-gcp:ufore:inntektsplanleggeren-backend"
    - name: "URL_PSELV_INNTEKTSPLANLEGGER"
      value: "https://www.nav.no/pselv/inntektsplanlegger/innledning.jsf?context=ut&simpleMode=true"
  envFrom:
    - secret: inntektsplanleggeren-frontend-unleash-api-token
