apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: inntektsplanleggeren-frontend-veileder
  namespace: pensjonselvbetjening
  labels:
    team: pensjonselvbetjening
  annotations:
    nais.io/run-as-user: "101" # nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{ image }}"
  ingresses:
    - https://intern.nav.no/uforetrygd/selvbetjening/inntektsplanleggeren
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /internal/health/health
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  azure:
    sidecar:
      autoLogin: true
      enabled: true
    application:
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" # SAKSBEHANDLER
          - id: "959ead5b-99b5-466b-a0ff-5fdbc687517b" # VEILEDER
          - id: "7845a796-1516-4d14-b500-fd65c001f35c" # BRUKERHJELPA
          - id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b" # OKONOMI
      enabled: true
      tenant: nav.no

  accessPolicy:
    outbound:
      rules:
        - application: inntektsplanleggeren-backend
          cluster: prod-gcp
          namespace: pensjonselvbetjening
  env:
    - name: MODE
      value: veileder
    - name: "INNTEKTSPLANLEGGEREN_BACKEND_URL"
      value: "http://inntektsplanleggeren-backend"
    - name: "INNTEKTSPLANLEGGEREN_BACKEND_SCOPE"
      value: "api://prod-gcp.pensjonselvbetjening.inntektsplanleggeren-backend/.default"
  envFrom:
    - secret: inntektsplanleggeren-frontend-unleash-api-token
