spring.main.web-application-type=servlet
server.error.include-message=always
server.max-http-request-header-size=16KB
spring.main.banner-mode=off

oauth2.azureAd.clientId=${AZURE_APP_CLIENT_ID}
oauth2.azureAd.clientSecret=${AZURE_APP_CLIENT_SECRET}
oauth2.azureAd.issuer=${AZURE_OPENID_CONFIG_ISSUER}
oauth2.azureAd.jsonWebKeyUri=${AZURE_OPENID_CONFIG_JWKS_URI}
oauth2.azureAd.tokenEndpoint=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}

oauth2.tokenX.clientId=${TOKEN_X_CLIENT_ID}
oauth2.tokenX.issuer=${TOKEN_X_ISSUER}
oauth2.tokenX.jsonWebKeyUri=${TOKEN_X_JWKS_URI}
oauth2.tokenX.tokenEndpoint=${TOKEN_X_TOKEN_ENDPOINT}
oauth2.tokenX.privateJwk=${TOKEN_X_PRIVATE_JWK}

fullmakt.endpoint.url=${FULLMAKT_URL}
fullmakt.scope=${FULLMAKT_SCOPE}
fullmakt.audience=${FULLMAKT_AUDIENCE}

parallellesannheter.endpoint.url=${PARALLELLE_SANNHETER_URL}

pdl.endpoint.url=${PDL_URL}
pdl.scope=${PDL_SCOPE}
pdl.audience=${PDL_AUDIENCE}

pen.endpoint.url=${PEN_URL}
pen.scope=${PEN_SCOPE}
pen.audience=${PEN_AUDIENCE}

skjerming.endpoint.url=${SKJERMING_URL}
skjerming.scope=${SKJERMING_SCOPE}

inntektskomponenten.endpoint.url=${INNTEKTSKOMPONENTEN_URL}
inntektskomponenten.scope=${INNTEKTSKOMPONENTEN_SCOPE}
inntektskomponenten.audience=${INNTEKTSKOMPONENTEN_AUD}

ereg-services.endpoint.url=${EREG_SERVICES_URL}