parallellesannheter.endpoint.url=https://pensjon-parallelle-sannheter.intern.dev.nav.no

pen.audience=dev-fss:pensjon-q2:pensjon-pen-q2
pen.endpoint.url=https://pensjon-pen-q2.dev.adeo.no
#pen.endpoint.url=http://localhost:8089
pen.scope=api://dev-fss.pensjon-q2.pensjon-pen-q2/.default

pdl.endpoint.url=https://pdl-api.dev-fss-pub.nais.io/graphql
pdl.scope=api://dev-fss.pdl.pdl-api/.default
pdl.audience=dev-fss:pdl:pdl-api

fullmakt.endpoint.url=https://pensjon-representasjon-q2.dev-fss-pub.nais.io
fullmakt.scope=api://dev-fss.pensjon-person.pensjon-representasjon-q2/.default
fullmakt.audience=dev-fss:pensjon-person:pensjon-representasjon-q2

skjerming.endpoint.url=https://skjermede-personer-pip.intern.dev.nav.no
skjerming.scope=api://dev-gcp.nom.skjermede-personer-pip/.default

inntektskomponenten.endpoint.url=https://team-inntekt-proxy.dev-fss-pub.nais.io/proxy/inntektskomponenten-q2/rs
inntektskomponenten.scope=api://dev-fss.team-inntekt.inntektskomponenten/.default
inntektskomponenten.audience=dev-fss.team-inntekt.inntektskomponenten

ereg-services.endpoint.url=https://ereg-services-q2.dev.intern.nav.no/

pensjon-brukerhjelpa-tilgang.group.id=9e122ddd-e542-4cc1-a7eb-92c99140fe0e
pensjon-okonomi-tilgang.group.id=05ae245b-7b47-428a-9074-4ff6b59eddbc
pensjon-saksbehandler-tilgang.group.id=8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf
pensjon-veileder-tilgang.group.id=a3f91493-1ab8-4b64-a544-0a77cbba9240
strengt-fortrolig-tilgang.group.id=dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
fortrolig-tilgang.group.id=ea930b6b-9397-44d9-b9e6-f4cf527a632a
skjermet-tilgang.group.id=dbe4ad45-320b-4e9a-aaa1-73cca4ee124d

oauth2.tokenX.clientId=${TOKEN_X_CLIENT_ID:dev-gcp:pensjonselvbetjening:inntektsplanleggeren-backend-q2}
oauth2.tokenX.issuer=${TOKEN_X_ISSUER:https://tokenx.dev-gcp.nav.cloud.nais.io}
oauth2.tokenX.jsonWebKeyUri=${TOKEN_X_JWKS_URI:https://tokenx.dev-gcp.nav.cloud.nais.io/jwks}
oauth2.tokenX.tokenEndpoint=${TOKEN_X_TOKEN_ENDPOINT:https://tokenx.dev-gcp.nav.cloud.nais.io/token}
oauth2.tokenX.privateJwk=${TOKEN_X_PRIVATE_JWK}

oauth2.azureAd.clientId=${AZURE_APP_CLIENT_ID:0454c152-6146-4cb6-9495-fa6f951cbcb9}
oauth2.azureAd.clientSecret=${AZURE_APP_CLIENT_SECRET}
oauth2.azureAd.issuer=${AZURE_OPENID_CONFIG_ISSUER:https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0}
oauth2.azureAd.jsonWebKeyUri=${AZURE_OPENID_CONFIG_JWKS_URI:https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/discovery/v2.0/keys}
oauth2.azureAd.tokenEndpoint=${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token}