parallellesannheter.endpoint.url=https://pensjon-parallelle-sannheter.intern.dev.nav.no

pen.audience=dev-fss:pensjon-q2:pensjon-pen-q2
pen.endpoint.url=https://pensjon-pen-q2.dev.adeo.no
pen.scope=api://dev-fss.pensjon-q2.pensjon-pen-q2/.default

pdl.endpoint.url=https://pdl-api.dev-fss-pub.nais.io/graphql
pdl.scope=api://dev-fss.pdl.pdl-api/.default
pdl.audience=dev-fss:pdl:pdl-api

fullmakt.endpoint.url=https://pensjon-representasjon-q2.dev-fss-pub.nais.io
fullmakt.scope=api://dev-fss.pensjon-person.pensjon-representasjon-q2/.default
fullmakt.audience=dev-fss:pensjon-person:pensjon-representasjon-q2

skjerming.endpoint.url=https://skjermede-personer-pip.intern.dev.nav.no
skjerming.scope=api://dev-gcp.nom.skjermede-personer-pip/.default

strengt-fortrolig-tilgang.group.id=dbe4ad45-320b-4e9a-aaa1-73cca4ee124d
fortrolig-tilgang.group.id=ea930b6b-9397-44d9-b9e6-f4cf527a632a
skjermet-tilgang.group.id=dbe4ad45-320b-4e9a-aaa1-73cca4ee124d