query($ident: ID!){
    hentPerson(ident: $ident){
        foedsel{
            foedselsdato
            folkeregistermetadata {
                ajourholdstidspunkt
                gyldighetstidspunkt
            }
            metadata {
                master
                endringer {
                    registrert
                    kilde
                    registrertAv
                    systemkilde
                    type
                }
                historisk
            }
        }
    }
}