export enum MessageCodes {
  USER_HAS_NO_UFORE = 'USER_HAS_NO_UFORE',
  USER_HAS_NO_LOPENDE_VEDTAK_YET = 'USER_HAS_NO_LOPENDE_VEDTAK_YET',
  ILLEGAL_INNTEKT_FIELD_VALUE = 'ILLEGAL_INNTEKT_FIELD_VALUE',
  ARBEIDSINNTEKT_GIVEN_SMALLER_THAN_HITTIL_I_AAR = 'ARBEIDSINNTEKT_GIVEN_SMALLER_THAN_HITTIL_I_AAR',
  ANDRE_YTELSER_SMALLER_THAN_HITTIL_I_AAR = 'ANDRE_YTELSER_SMALLER_THAN_HITTIL_I_AAR',
  ONE_OR_MORE_INNTEKT_HAS_STATUS_REGISTRERT = 'ONE_OR_MORE_INNTEKT_HAS_STATUS_REGISTRERT',
  EPS_INNTEKT_CHANGED = 'EPS_INNTEKT_CHANGED',
  ILLEGAL_MONTH_DECEMBER_THIS_YEAR = 'ILLEGAL_MONTH_DECEMBER_THIS_YEAR',
  INNTEKT_ONLY_RELEVANT_WHEN_BARNETILLEGG = 'INNTEKT_ONLY_RELEVANT_WHEN_BARNETILLEGG',
  MISSING_RELEVANT_INNTEKTER_WHEN_BARNETILLEGG = 'MISSING_RELEVANT_INNTEKTER_WHEN_BARNETILLEGG',
  EPS_INNTEKT_ONLY_RELEVANT_WHEN_BARNETILLEGG_FELLESBARN = 'EPS_INNTEKT_ONLY_RELEVANT_WHEN_BARNETILLEGG_FELLESBARN',
  MISSING_RELEVANT_EPS_INNTEKT_WHEN_BARNETILLEGG_FELLESBARN = 'MISSING_RELEVANT_EPS_INNTEKT_WHEN_BARNETILLEGG_FELLESBARN',
  FIELD_CAN_NOT_BE_NULL = 'FIELD_CAN_NOT_BE_NULL',
  OPPGITT_INNTEKT_OVER_INNTEKTSTAK = 'OPPGITT_INNTEKT_OVER_INNTEKTSTAK',
  OPPGITT_INNTEKT_GIVES_LOWER_UFORETRYGD_THAN_ALREADY_UTBETALT = 'OPPGITT_INNTEKT_GIVES_LOWER_UFORETRYGD_THAN_ALREADY_UTBETALT',
  OPPGITT_INNTEKT_GIVES_MORE_UFORETRYGD_THAN_ALREADY_UTBETALT = 'OPPGITT_INNTEKT_GIVES_MORE_UFORETRYGD_THAN_ALREADY_UTBETALT',
  FAKTOROMREGNET_ELLER_MANUELT_OVERSTYRT = 'FAKTOROMREGNET_ELLER_MANUELT_OVERSTYRT',
  OPEN_INNTEKTSENDRING_KRAV = 'OPEN_INNTEKTSENDRING_KRAV',
  SIMULERING_CONTAINS_MOTREGNING = 'SIMULERING_CONTAINS_MOTREGNING',
  SIMULERING_CONTAINS_OPPHORTE_YTELSER = 'SIMULERING_CONTAINS_OPPHORTE_YTELSER'
}

export enum MessageTypes {
  ERROR = 'ERROR',
  WARNING = 'WARNING',
  INFO = 'INFO',
}
