export enum StatusCodes {
    BEHANDLET_MEDFOERER_ENDRING = "BEHANDLET_MEDFOERER_ENDRING",
    BEHANDLET_MEDFOERER_INGEN_ENDRING = "BEHANDLET_MEDFOERER_INGEN_ENDRING",
    TIL_BEHANDLING = "TIL_BEHANDLING",
}