name: Apply alerts

on:
  push:
    branches:
      - main
    paths:
        - '.github/workflows/applyAlerts.yml'
        - 'alerts/**'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts/alerts.yaml
          TEAM: ufore
