name: Apply alerts

on:
  push:
    branches:
      - main
    paths:
        - '.github/workflows/applyAlerts.yml'
        - 'alerts/**'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts/alerts.yaml
          TEAM: ufore
