name: "(Automerge): Inntektsplanleggeren backend"
on:
  workflow_dispatch:
  schedule:
    # 8 betyr 9 vintertid og 10 sommertid
    - cron: '0,10,20,30 8 * * 1,2,3,4,5'

jobs:
  merge-dependabot-pr-inntektsplanleggeren-backend:
    name: Merge dependabot pr for inntektsplanleggeren backend
    uses: ./.github/workflows/merge-dependabot-pr.yml@main
    permissions:
      actions: write
      checks: read
      contents: write
      pull-requests: write
      statuses: read
    with:
      workflow-id: prod-inntektsplanleggeren-backend-deploy.yml
      label: automerge/inntektsplanleggeren-backend
