name: "(Automerge): Inntektsplanleggeren frontend"
on:
  workflow_dispatch:
  schedule:
    - cron: '35,40,45,50 11 * * 1,2,3,4,5'

jobs:
  merge-dependabot-pr-inntektsplanleggeren-frontend:
    name: Merge dependabot pr for inntektsplanleggeren frontend
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/merge-dependabot-pr.yml@main
    permissions:
      actions: write
      checks: read
      contents: write
      pull-requests: write
      statuses: read
    with:
      workflow-id: prod-inntektsplanleggeren-frontend-deploy.yml
      label: automerge/inntektsplanleggeren-frontend
