name: Bygg inntektsplanleggeren-frontend
on:
  workflow_dispatch:
  push:
    paths:
      - inntektsplanleggeren-frontend/**
    branches-ignore:
      - main  # Bygges allerede av deploy-workflow

jobs:
  build-frontend:
    name: Bygg med node
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inntektsplanleggeren-frontend
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          cache-dependency-path: inntektsplanleggeren-frontend/package-lock.json

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v5
        with:
          path: |
            inntektsplanleggeren-frontend/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Installer avhengigheter
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Lint
        run: npm run check

      - name: Bygg med node
        run: npm run build
        env:
          FARO_TELEMETRY_URL: 'https://telemetry.ekstern.dev.nav.no/collect'
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
