name: Build inntektsplanleggeren backend
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main  # Bygges allerede av deploy-workflow

jobs:
  build-backend:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/build-maven.yml@main
    name: Build backend application
    permissions:
      actions: read
      contents: read
    secrets: inherit
    with:
      path: /inntektsplanleggeren-backend
      java-version: 21