name: Deploy alerts
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
        - 'inntektsplanleggeren-backend/.nais/alerts-prod.yml'
        - 'inntektsplanleggeren-frontend-borger/.nais/alerts-prod-borger.yml'
        - 'inntektsplanleggeren-frontend-veileder/.nais/alerts-prod-veileder.yml'
jobs:
  deploy-inntektsplanleggeren-backend-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: inntektsplanleggeren-backend/.nais/alerts-prod.yml
      production-cluster: prod-gcp

  deploy-inntektsplanleggeren-frontend-borger-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: inntektsplanleggeren-frontend/.nais/alerts-prod-borger.yml
      production-cluster: prod-gcp

  deploy-inntektsplanleggeren-frontend-veileder-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: inntektsplanleggeren-frontend/.nais/alerts-prod-veileder.yml
      production-cluster: prod-gcp
