name: Deploy alerts
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.nais/alderspensjon-endringssoknad-backend/alerts/**'
      - 'dinpensjon-backend/.nais/alerts-prod.yml'
      - 'dinpensjon-frontend-borger/.nais/alerts-prod-borger.yml'
      - 'dinpensjon-frontend-veileder/.nais/alerts-prod-veileder.yml'
      - '.nais/familieforhold-backend/alerts/**'
      - '.nais/familieforhold-frontend-borger/alerts/**'
      - '.nais/familieforhold-frontend-veileder/alerts/**'
      - '.nais/opptjening-overforomsorgsopptjening-backend/alerts/**'

jobs:
  deploy-alerspensjon-endringssoknad-backend-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: .nais/alderspensjon-endringssoknad-backend/alerts/alerts-prod.yml
      production-cluster: prod-gcp

  deploy-alerspensjon-endringssoknad-frontend-borger-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: .nais/alderspensjon-endringssoknad-frontend-borger/alerts/alerts-prod.yml
      production-cluster: prod-gcp

  deploy-alerspensjon-endringssoknad-frontend-veileder-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: .nais/alderspensjon-endringssoknad-frontend-veileder/alerts/alerts-prod.yml
      production-cluster: prod-gcp

  deploy-familieforhold-backend-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: familieforhold-backend/.nais/alerts-prod.yml
      production-cluster: prod-gcp

  deploy-familieforhold-frontend-borger-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: familieforhold-frontend/.nais/alerts-prod-borger.yml
      production-cluster: prod-gcp

  deploy-familieforhold-frontend-veileder-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: familieforhold-frontend/.nais/alerts-prod-veileder.yml
      production-cluster: prod-gcp

  deploy-dinpensjon-backend-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: dinpensjon-backend/.nais/alerts-prod.yml
      production-cluster: prod-gcp

  deploy-dinpensjon-frontend-borger-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: dinpensjon-frontend/.nais/alerts-prod-borger.yml
      production-cluster: prod-gcp

  deploy-dinpensjon-frontend-veileder-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: dinpensjon-frontend/.nais/alerts-prod-veileder.yml
      production-cluster: prod-gcp

  deploy-uforetrygd-backend-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: uforetrygd-backend/.nais/alerts-prod.yml
      production-cluster: prod-gcp

  deploy-uforetrygd-frontend-borger-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: uforetrygd-frontend/.nais/alerts-prod-borger.yml
      production-cluster: prod-gcp

  deploy-uforetrygd-frontend-veileder-alerts:
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      nais-template-production: uforetrygd-frontend/.nais/alerts-prod-veileder.yml
      production-cluster: prod-gcp

#  deploy-opptjening-overforomsorgsopptjening-backend-alerts:
#    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy-alerts.yml@main
#    permissions:
#      contents: read
#      id-token: write
#    with:
#      nais-template-q2: .nais/opptjening-overforomsorgsopptjening-backend/alerts/alerts-q2.yml
#      nais-template-production: .nais/opptjening-overforomsorgsopptjening-backend/alerts/alerts-prod.yml
#      dev-cluster: dev-gcp
#      production-cluster: prod-gcp