name: "Dev: inntektsplanleggeren Backend (q2) deploy"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * SUN'

jobs:
  build-backend-and-publish-docker:
    name: Build backend application
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/build-backend-and-publish-docker.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      path: /inntektsplanleggeren-backend
      team: pensjonselvbetjening
      app: inntektsplanleggeren-backend
      java-version: 21
    secrets: inherit

  deploy-to-q2:
    needs: build-backend-and-publish-docker
    uses: navikt/pensjonsbruker-github-actions-workflows/.github/workflows/deploy.yml@main
    permissions:
      actions: read
      contents: read
      id-token: write
    with:
      cluster: dev-gcp
      image: ${{ needs.build-backend-and-publish-docker.outputs.image }}
      team: pensjonselvbetjening
      nais-template: inntektsplanleggeren-backend/.nais/dev.yaml
