#Hentet og modifisert fra https://github.com/navikt/pensjonsbruker-github-actions-workflows
name: Merge dependabot pr
on:
  workflow_call:
    inputs:
      workflow-id:
        required: false
        default: "build-and-deploy.yml"
        type: string
      label:
        required: false
        default: "automerge"
        type: string

jobs:
  merge-pullrequests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/github-script@v7
        env:
          WORKFLOW_ID: ${{ inputs.workflow-id }}
          LABEL: ${{ inputs.label }}
        with:
          script: |
            const { WORKFLOW_ID } = process.env
            const { LABEL } = process.env
            
            console.log("WORKFLOW_ID: " + WORKFLOW_ID)
            console.log("LABEL: " + LABEL)
            
            const today = new Date();
            
            if((today.getDate() >= 20 && today.getMonth == 11) || (today.getDate() <= 2 && today.getMonth() == 0)) {
                console.log('Skriptet kjører ikke i jula');
                return;
            }
            
            const pulls = await github.request('GET /repos/{owner}/{repo}/pulls?per_page=100', {
                owner: context.repo.owner,
                repo: context.repo.repo,
            })
            
            console.log("pulls: " + pulls.data.length)

            const filtrert = pulls.data
                .filter((it) => it.state == 'open')
                .filter((it) => !it.head.repo.fork)
                .filter((it) => it.labels.some((l) => l.name == LABEL))
                .map((it) => {
                    return {
                        title: it.title,
                        number: it.number,

                    }
                })
                .map(async (it) => {
                    const QUERY = `query($owner: String!, $repo: String!, $pull_number: Int!) {
                                          repository(owner: $owner, name:$repo) {
                                            pullRequest(number:$pull_number) {
                                              commits(last: 1) {
                                                nodes {
                                                  commit {
                                                    statusCheckRollup {
                                                      state
                                                    }







                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }`

                    const result = await github.graphql(QUERY, {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: it.number,
                    })
                    const [{ commit: lastCommit }] =
                        result.repository.pullRequest.commits.nodes

                    return {
                        title: it.title,
                        number: it.number,
                        checksOk: lastCommit.statusCheckRollup?.state === 'SUCCESS',
                    }
                })
            
            console.log("filtrert: " + filtrert.length)

            const allePrs = await Promise.all(filtrert)
            const mergeablePromise = allePrs
                .filter((it) => it.checksOk) //sjekker om alle githubsjekker er ok
                .map(async (it) => {
                    const prdata = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: it.number
                    })
                    return {
                        title: it.title,
                        number: it.number,
                        mergeable: prdata.data.mergeable
                    }
                })

            //mergeable er pr-er som faktisk kan merges
            const mergeable = (await Promise.all(mergeablePromise))
                .filter((it) => {
                  return it.mergeable;
                })
            console.log("mergeable: " + mergeable.length)
            
            //Merger første pr i mergeable
            if (mergeable.length > 0) {
                const pr = mergeable[0]
                console.log('Merger PR', pr.title)
                await github.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge', {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    merge_method: 'squash'
                })
            
              console.log('Starter main workflow')
            
            //Kjører neste workflow som definert i WORKFLOW_ID
              await github.request(
                  'POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches',
                  {
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      workflow_id: WORKFLOW_ID,
                      ref: 'main',
                  }
              )
            } else {
                console.log('Ingen PRer å merge')
            }