name: Run Playwright tests
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  run-playwright-tests:
    name: Run playwright for ${{ inputs.path }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.path }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18.18.1
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
