name: "Prod: Inntektsplanleggeren frontend deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - inntektsplanleggeren-frontend/**

concurrency:
  group: prod-inntektsplanleggeren-frontend-deploy
  cancel-in-progress: true

jobs:
  build-frontend-and-publish-docker-borger:
    name: Bygg inntektsplanleggeren-frontend-borger
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Bygg og publiser Docker-image
        uses: ./.github/actions/build-frontend
        id: build
        with:
          build_command: build:production
          reader_token: ${{ secrets.READER_TOKEN }}
          mode: borger

      - name: "Send slack-notifikasjon om bygget feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \":calc:*Bygg av inntektsplanleggeren-frontend (borger) før deploy til prod feilet* :bomb::hellmo:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/ufore-inntektsplanleggeren/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}


  build-frontend-and-publish-docker-veileder:
    name: Bygg inntektsplanleggeren-frontend-veileder
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Bygg og publiser Docker-image
        uses: ./.github/actions/build-frontend
        id: build
        with:
          build_command: build:production:veileder
          reader_token: ${{ secrets.READER_TOKEN }}
          mode: veileder

      - name: "Send slack-notifikasjon om bygget feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \":calc:*Bygg av inntektsplanleggeren-frontend (veileder) før deploy til prod feilet* :bomb::hellmo:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/ufore-inntektsplanleggeren/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  trivy-docker:
    needs: build-frontend-and-publish-docker-borger
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write
    steps:
      - uses: nais/login@d6ab5d83f735e9f155eb9d7d29cd20ae46820ea9 # v0
        with:
          team: ufore
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # 0.36.0
        with:
          image-ref: ${{ needs.build-frontend-and-publish-docker-borger.outputs.image }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true
      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        with:
          sarif_file: 'trivy.sarif'

  deploy-frontend-borger:
    needs: build-frontend-and-publish-docker-borger
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Deploy
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: inntektsplanleggeren-frontend/.nais/prod-borger.yml,inntektsplanleggeren-frontend/.nais/unleash-prod.yml
          IMAGE: ${{ needs.build-frontend-and-publish-docker-borger.outputs.image }}
          TEAM: ufore

      - name: "Send slack-notifikasjon om deploy til borger feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \":calc:*Deploy av inntektsplanleggeren-frontend (borger) til prod feilet* :bomb::fire:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/ufore-inntektsplanleggeren/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  deploy-frontend-veileder:
    needs: build-frontend-and-publish-docker-veileder
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Deploy
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: inntektsplanleggeren-frontend/.nais/prod-veileder.yml,inntektsplanleggeren-frontend/.nais/unleash-prod.yml
          IMAGE: ${{ needs.build-frontend-and-publish-docker-veileder.outputs.image }}
          TEAM: ufore

      - name: "Send slack-notifikasjon om deploy til veileder feiler"
        if: ${{ failure() }}
        run: |
          PAYLOAD="payload={ \"attachments\": [{\"color\": \"danger\", \"text\": \":calc:*Deploy av inntektsplanleggeren-frontend (veileder) til prod feilet* :bomb::fire:\nAnsvarlig: \${slack_id}\nCommit: <https://github.com/navikt/ufore-inntektsplanleggeren/commit/$GITHUB_SHA|$GITHUB_SHA>\" }] }"
          chmod +x "${GITHUB_WORKSPACE}/.github/notify-slack.sh"
          "${GITHUB_WORKSPACE}/.github/notify-slack.sh" "${SSH_KEY}" "${AUTHOR}" "${PAYLOAD}" "${WEBHOOK_URL}"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY_NOTIFY_TO_SLACK }}
          AUTHOR: ${{ github.actor }}
          WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
